<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CountryCurrencies;

class CountryCurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countrycurrencies = [
            [
                "id" => "1",
                "aplha_code2" => "AD",
                "aplha_code3" => "AND",
                "numeric_code" => "20",
                "country_name" => "Andorra",
                "currency_name" => "Euro",
                "currency_code" => "EUR",
                "currency_symbol" => "€",
                "currency_column" => "cur_eur",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "2",
                "aplha_code2" => "AE",
                "aplha_code3" => "ARE",
                "numeric_code" => "784",
                "country_name" => "United Arab Emirates",
                "currency_name" => "Dirham",
                "currency_code" => "AED",
                "currency_symbol" => "AED",
                "currency_column" => "cur_aed",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "3",
                "aplha_code2" => "AF",
                "aplha_code3" => "AFG",
                "numeric_code" => "4",
                "country_name" => "Afghanistan",
                "currency_name" => "Afghani",
                "currency_code" => "AFN",
                "currency_symbol" => "AFN",
                "currency_column" => "cur_afn",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "4",
                "aplha_code2" => "AL",
                "aplha_code3" => "ALB",
                "numeric_code" => "8",
                "country_name" => "Albania",
                "currency_name" => "Albanian lek",
                "currency_code" => "ALL",
                "currency_symbol" => "L",
                "currency_column" => "cur_all",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "5",
                "aplha_code2" => "AM",
                "aplha_code3" => "ARM",
                "numeric_code" => "51",
                "country_name" => "Armenia",
                "currency_name" => "Armenian dram",
                "currency_code" => "AMD",
                "currency_symbol" => "AMD",
                "currency_column" => "cur_amd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "6",
                "aplha_code2" => "AO",
                "aplha_code3" => "AGO",
                "numeric_code" => "24",
                "country_name" => "Angola",
                "currency_name" => "Angolan kwanza",
                "currency_code" => "AOA",
                "currency_symbol" => "Kz",
                "currency_column" => "cur_aoa",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "7",
                "aplha_code2" => "AR",
                "aplha_code3" => "ARG",
                "numeric_code" => "32",
                "country_name" => "Argentina",
                "currency_name" => "Argentine peso",
                "currency_code" => "ARS",
                "currency_symbol" => "$",
                "currency_column" => "cur_ars",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "8",
                "aplha_code2" => "AT",
                "aplha_code3" => "AUT",
                "numeric_code" => "40",
                "country_name" => "Austria",
                "currency_name" => "Euro",
                "currency_code" => "EUR",
                "currency_symbol" => "€",
                "currency_column" => "cur_eur_at",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "9",
                "aplha_code2" => "AU",
                "aplha_code3" => "AUS",
                "numeric_code" => "36",
                "country_name" => "Australia",
                "currency_name" => "Australian Dollar",
                "currency_code" => "AUD",
                "currency_symbol" => "A$",
                "currency_column" => "cur_aud",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "10",
                "aplha_code2" => "AW",
                "aplha_code3" => "ABW",
                "numeric_code" => "533",
                "country_name" => "Aruba",
                "currency_name" => "Aruban florin",
                "currency_code" => "AWG",
                "currency_symbol" => "ƒ",
                "currency_column" => "cur_awg",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "11",
                "aplha_code2" => "AZ",
                "aplha_code3" => "AZE",
                "numeric_code" => "31",
                "country_name" => "Azerbaijan",
                "currency_name" => "Azerbaijani manat",
                "currency_code" => "AZN",
                "currency_symbol" => "&#8380;",
                "currency_column" => "cur_azn",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "12",
                "aplha_code2" => "BA",
                "aplha_code3" => "BIH",
                "numeric_code" => "70",
                "country_name" => "Bosnia and Herzegovina",
                "currency_name" => "Mark",
                "currency_code" => "BAM",
                "currency_symbol" => "KM",
                "currency_column" => "cur_bam",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "13",
                "aplha_code2" => "BB",
                "aplha_code3" => "BRB",
                "numeric_code" => "52",
                "country_name" => "Barbados",
                "currency_name" => "Barbadian dollar",
                "currency_code" => "BBD",
                "currency_symbol" => "Bds$",
                "currency_column" => "cur_bbd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "14",
                "aplha_code2" => "BD",
                "aplha_code3" => "BGD",
                "numeric_code" => "50",
                "country_name" => "Bangladesh",
                "currency_name" => "Bangladeshi taka",
                "currency_code" => "BDT",
                "currency_symbol" => "Tk",
                "currency_column" => "cur_bdt",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "15",
                "aplha_code2" => "BE",
                "aplha_code3" => "BEL",
                "numeric_code" => "56",
                "country_name" => "Belgium",
                "currency_name" => "Euro",
                "currency_code" => "EUR",
                "currency_symbol" => "€",
                "currency_column" => "cur_eur_be",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "16",
                "aplha_code2" => "BG",
                "aplha_code3" => "BGR",
                "numeric_code" => "100",
                "country_name" => "Bulgaria",
                "currency_name" => "Bulgarian lev",
                "currency_code" => "BGN",
                "currency_symbol" => "лв",
                "currency_column" => "cur_bgn",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "17",
                "aplha_code2" => "BH",
                "aplha_code3" => "BHR",
                "numeric_code" => "48",
                "country_name" => "Bahrain",
                "currency_name" => "Bahraini dinar",
                "currency_code" => "BHD",
                "currency_symbol" => "BD",
                "currency_column" => "cur_bhd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "18",
                "aplha_code2" => "BI",
                "aplha_code3" => "BDI",
                "numeric_code" => "108",
                "country_name" => "Burundi",
                "currency_name" => "Burundian franc",
                "currency_code" => "BIF",
                "currency_symbol" => "Fbu",
                "currency_column" => "cur_bif",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "19",
                "aplha_code2" => "BM",
                "aplha_code3" => "BMU",
                "numeric_code" => "60",
                "country_name" => "Bermuda",
                "currency_name" => "Bermudian dollar",
                "currency_code" => "BMD",
                "currency_symbol" => "BM$",
                "currency_column" => "cur_bmd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "20",
                "aplha_code2" => "BN",
                "aplha_code3" => "BRN",
                "numeric_code" => "96",
                "country_name" => "Brunei Darussalam",
                "currency_name" => "Brunei dollar",
                "currency_code" => "BND",
                "currency_symbol" => "B$",
                "currency_column" => "cur_bnd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "21",
                "aplha_code2" => "BO",
                "aplha_code3" => "BOL",
                "numeric_code" => "68",
                "country_name" => "Bolivia, Plurinational State of",
                "currency_name" => "Bolivian boliviano",
                "currency_code" => "BOB",
                "currency_symbol" => "Bs",
                "currency_column" => "cur_bob",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "22",
                "aplha_code2" => "BR",
                "aplha_code3" => "BRA",
                "numeric_code" => "76",
                "country_name" => "Brazil",
                "currency_name" => "Brazilian real",
                "currency_code" => "BRL",
                "currency_symbol" => "R$",
                "currency_column" => "cur_brl",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "23",
                "aplha_code2" => "BS",
                "aplha_code3" => "BHS",
                "numeric_code" => "44",
                "country_name" => "Bahamas",
                "currency_name" => "Bahamian dollar",
                "currency_code" => "BSD",
                "currency_symbol" => "B$",
                "currency_column" => "cur_bsd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "24",
                "aplha_code2" => "BT",
                "aplha_code3" => "BTN",
                "numeric_code" => "64",
                "country_name" => "Bhutan",
                "currency_name" => "Bhutanese ngultrum",
                "currency_code" => "BTN",
                "currency_symbol" => "Nu",
                "currency_column" => "cur_btn",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "25",
                "aplha_code2" => "BW",
                "aplha_code3" => "BWA",
                "numeric_code" => "72",
                "country_name" => "Botswana",
                "currency_name" => "Botswana pula",
                "currency_code" => "BWP",
                "currency_symbol" => "P",
                "currency_column" => "cur_bwp",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "26",
                "aplha_code2" => "BZ",
                "aplha_code3" => "BLZ",
                "numeric_code" => "84",
                "country_name" => "Belize",
                "currency_name" => "Belize dollar",
                "currency_code" => "BZD",
                "currency_symbol" => "BZ$",
                "currency_column" => "cur_bzd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "27",
                "aplha_code2" => "CA",
                "aplha_code3" => "CAN",
                "numeric_code" => "124",
                "country_name" => "Canada",
                "currency_name" => "Canadian dollar",
                "currency_code" => "CAD",
                "currency_symbol" => "C$",
                "currency_column" => "cur_cad",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "28",
                "aplha_code2" => "CC",
                "aplha_code3" => "CCK",
                "numeric_code" => "166",
                "country_name" => "Cocos (Keeling) Islands",
                "currency_name" => "Australian dollar",
                "currency_code" => "AUD",
                "currency_symbol" => "A$",
                "currency_column" => "cur_aud_ca",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "29",
                "aplha_code2" => "CD",
                "aplha_code3" => "COD",
                "numeric_code" => "180",
                "country_name" => "Congo, The Democratic Republic of The",
                "currency_name" => "Congolese franc",
                "currency_code" => "CDF",
                "currency_symbol" => "FC",
                "currency_column" => "cur_cdf",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "30",
                "aplha_code2" => "CG",
                "aplha_code3" => "COG",
                "numeric_code" => "178",
                "country_name" => "Congo",
                "currency_name" => "Congolese franc",
                "currency_code" => "CDF",
                "currency_symbol" => "FC",
                "currency_column" => "cur_cdf",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "31",
                "aplha_code2" => "CH",
                "aplha_code3" => "CHE",
                "numeric_code" => "756",
                "country_name" => "Switzerland",
                "currency_name" => "Swiss Franc",
                "currency_code" => "CHF",
                "currency_symbol" => "Fr",
                "currency_column" => "cur_chf_se",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "32",
                "aplha_code2" => "CK",
                "aplha_code3" => "COK",
                "numeric_code" => "184",
                "country_name" => "Cook Islands",
                "currency_name" => "New Zealand dollar",
                "currency_code" => "NZD",
                "currency_symbol" => "NZ$",
                "currency_column" => "cur_ck_nzd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "33",
                "aplha_code2" => "CL",
                "aplha_code3" => "CHL",
                "numeric_code" => "152",
                "country_name" => "Chile",
                "currency_name" => "Chilean peso",
                "currency_code" => "CLP",
                "currency_symbol" => "CLP",
                "currency_column" => "cur_clp",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "34",
                "aplha_code2" => "CN",
                "aplha_code3" => "CHN",
                "numeric_code" => "156",
                "country_name" => "China",
                "currency_name" => "Chinese Yuan",
                "currency_code" => "CNY",
                "currency_symbol" => "¥",
                "currency_column" => "cur_cny",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "35",
                "aplha_code2" => "CO",
                "aplha_code3" => "COL",
                "numeric_code" => "170",
                "country_name" => "Colombia",
                "currency_name" => "Colombian peso",
                "currency_code" => "COP",
                "currency_symbol" => "COP",
                "currency_column" => "cur_cop",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "36",
                "aplha_code2" => "CR",
                "aplha_code3" => "CRI",
                "numeric_code" => "188",
                "country_name" => "Costa Rica",
                "currency_name" => "Costa Rican colón",
                "currency_code" => "CRC",
                "currency_symbol" => "₡",
                "currency_column" => "cur_crc",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "37",
                "aplha_code2" => "CU",
                "aplha_code3" => "CUB",
                "numeric_code" => "192",
                "country_name" => "Cuba",
                "currency_name" => "Cuban Peso",
                "currency_code" => "CUP",
                "currency_symbol" => "₱",
                "currency_column" => "cur_cup",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "38",
                "aplha_code2" => "CV",
                "aplha_code3" => "CPV",
                "numeric_code" => "132",
                "country_name" => "Cabo Verde",
                "currency_name" => "Cape Verdean Escudo",
                "currency_code" => "CVE",
                "currency_symbol" => "Esc",
                "currency_column" => "cur_cve",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "39",
                "aplha_code2" => "CY",
                "aplha_code3" => "CYP",
                "numeric_code" => "196",
                "country_name" => "Cyprus",
                "currency_name" => "Euro",
                "currency_code" => "EUR",
                "currency_symbol" => "€",
                "currency_column" => "cur_eur_cy",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "40",
                "aplha_code2" => "CZ",
                "aplha_code3" => "CZE",
                "numeric_code" => "203",
                "country_name" => "Czech Republic",
                "currency_name" => "Czech koruna",
                "currency_code" => "CZK",
                "currency_symbol" => "Kč",
                "currency_column" => "cur_czk",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "41",
                "aplha_code2" => "DE",
                "aplha_code3" => "DEU",
                "numeric_code" => "276",
                "country_name" => "Germany",
                "currency_name" => "Euro",
                "currency_code" => "EUR",
                "currency_symbol" => "€",
                "currency_column" => "cur_eur_gr",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "42",
                "aplha_code2" => "DJ",
                "aplha_code3" => "DJI",
                "numeric_code" => "262",
                "country_name" => "Djibouti",
                "currency_name" => "Djiboutian franc",
                "currency_code" => "DJF",
                "currency_symbol" => "Fdj",
                "currency_column" => "cur_djf",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "43",
                "aplha_code2" => "DK",
                "aplha_code3" => "DNK",
                "numeric_code" => "208",
                "country_name" => "Denmark",
                "currency_name" => "Danish krone",
                "currency_code" => "DKK",
                "currency_symbol" => "Kr",
                "currency_column" => "cur_dkk",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "44",
                "aplha_code2" => "DO",
                "aplha_code3" => "DOM",
                "numeric_code" => "214",
                "country_name" => "Dominican Republic",
                "currency_name" => "Eastern Caribbean dollar",
                "currency_code" => "DOP",
                "currency_symbol" => "EC$",
                "currency_column" => "cur_dop",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "45",
                "aplha_code2" => "DZ",
                "aplha_code3" => "DZA",
                "numeric_code" => "12",
                "country_name" => "Algeria",
                "currency_name" => "Algerian dinar",
                "currency_code" => "DZD",
                "currency_symbol" => "DZD",
                "currency_column" => "cur_dzd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "46",
                "aplha_code2" => "EE",
                "aplha_code3" => "EST",
                "numeric_code" => "233",
                "country_name" => "Estonia",
                "currency_name" => "Euro",
                "currency_code" => "EUR",
                "currency_symbol" => "€",
                "currency_column" => "cur_eur_ee",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "47",
                "aplha_code2" => "EG",
                "aplha_code3" => "EGY",
                "numeric_code" => "818",
                "country_name" => "Egypt",
                "currency_name" => "Egyptian pound",
                "currency_code" => "EGP",
                "currency_symbol" => "E£",
                "currency_column" => "cur_egp",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "48",
                "aplha_code2" => "ES",
                "aplha_code3" => "ESP",
                "numeric_code" => "724",
                "country_name" => "Spain",
                "currency_name" => "Euro",
                "currency_code" => "EUR",
                "currency_symbol" => "€",
                "currency_column" => "cur_eur_es",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "49",
                "aplha_code2" => "ET",
                "aplha_code3" => "ETH",
                "numeric_code" => "231",
                "country_name" => "Ethiopia",
                "currency_name" => "Ethiopian birr",
                "currency_code" => "ETB",
                "currency_symbol" => "Br",
                "currency_column" => "cur_etb",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "50",
                "aplha_code2" => "FI",
                "aplha_code3" => "FIN",
                "numeric_code" => "246",
                "country_name" => "Finland",
                "currency_name" => "Euro",
                "currency_code" => "EUR",
                "currency_symbol" => "€",
                "currency_column" => "cur_eur_fi",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "51",
                "aplha_code2" => "FJ",
                "aplha_code3" => "FJI",
                "numeric_code" => "242",
                "country_name" => "Fiji",
                "currency_name" => "Fijian dollar",
                "currency_code" => "FJD",
                "currency_symbol" => "FJ$",
                "currency_column" => "cur_fjd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "52",
                "aplha_code2" => "FR",
                "aplha_code3" => "FRA",
                "numeric_code" => "250",
                "country_name" => "France",
                "currency_name" => "Euro",
                "currency_code" => "EUR",
                "currency_symbol" => "€",
                "currency_column" => "cur_eur_fr",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "53",
                "aplha_code2" => "GB",
                "aplha_code3" => "GBR",
                "numeric_code" => "826",
                "country_name" => "United Kingdom",
                "currency_name" => "Pound",
                "currency_code" => "GBP",
                "currency_symbol" => "£",
                "currency_column" => "cur_gbp",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "54",
                "aplha_code2" => "GE",
                "aplha_code3" => "GEO",
                "numeric_code" => "268",
                "country_name" => "Georgia",
                "currency_name" => "Georgian Lari",
                "currency_code" => "GEL",
                "currency_symbol" => "GEL",
                "currency_column" => "cur_gel",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "55",
                "aplha_code2" => "GH",
                "aplha_code3" => "GHA",
                "numeric_code" => "288",
                "country_name" => "Ghana",
                "currency_name" => "Ghanaian Cedi ",
                "currency_code" => "GHS",
                "currency_symbol" => "GH¢",
                "currency_column" => "cur_ghs",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "56",
                "aplha_code2" => "GI",
                "aplha_code3" => "GIB",
                "numeric_code" => "292",
                "country_name" => "Gibraltar",
                "currency_name" => "Gibraltar pound",
                "currency_code" => "GIP",
                "currency_symbol" => "GIB£",
                "currency_column" => "cur_gip",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "57",
                "aplha_code2" => "GM",
                "aplha_code3" => "GMB",
                "numeric_code" => "270",
                "country_name" => "Gambia",
                "currency_name" => "Gambian dalasi",
                "currency_code" => "GMD",
                "currency_symbol" => "D",
                "currency_column" => "cur_gmd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "58",
                "aplha_code2" => "GN",
                "aplha_code3" => "GIN",
                "numeric_code" => "324",
                "country_name" => "Guinea",
                "currency_name" => "Guinean franc",
                "currency_code" => "GNF",
                "currency_symbol" => "GFr",
                "currency_column" => "cur_gnf",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "59",
                "aplha_code2" => "GR",
                "aplha_code3" => "GRC",
                "numeric_code" => "300",
                "country_name" => "Greece",
                "currency_name" => "Euro",
                "currency_code" => "EUR",
                "currency_symbol" => "€",
                "currency_column" => "cur_eur_gr",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "60",
                "aplha_code2" => "GT",
                "aplha_code3" => "GTM",
                "numeric_code" => "320",
                "country_name" => "Guatemala",
                "currency_name" => "Guatemalan Quetzal",
                "currency_code" => "GTQ",
                "currency_symbol" => "Q",
                "currency_column" => "cur_gtq",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "61",
                "aplha_code2" => "GY",
                "aplha_code3" => "GUY",
                "numeric_code" => "328",
                "country_name" => "Guyana",
                "currency_name" => "Guyanaese Dollar",
                "currency_code" => "GYD",
                "currency_symbol" => "GY$",
                "currency_column" => "cur_gyd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "62",
                "aplha_code2" => "HK",
                "aplha_code3" => "HKG",
                "numeric_code" => "344",
                "country_name" => "Hong Kong",
                "currency_name" => "Hong Kong dollar",
                "currency_code" => "HKD",
                "currency_symbol" => "HK$",
                "currency_column" => "cur_hkd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "63",
                "aplha_code2" => "HN",
                "aplha_code3" => "HND",
                "numeric_code" => "340",
                "country_name" => "Honduras",
                "currency_name" => "Honduran Lempira",
                "currency_code" => "HNL",
                "currency_symbol" => "L",
                "currency_column" => "cur_hnl",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "64",
                "aplha_code2" => "HR",
                "aplha_code3" => "HRV",
                "numeric_code" => "191",
                "country_name" => "Croatia",
                "currency_name" => "Croatian Kuna",
                "currency_code" => "HRK",
                "currency_symbol" => "kn",
                "currency_column" => "cur_hrk",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "65",
                "aplha_code2" => "HT",
                "aplha_code3" => "HTI",
                "numeric_code" => "332",
                "country_name" => "Haiti",
                "currency_name" => "Haitian Gourde",
                "currency_code" => "HTG",
                "currency_symbol" => "G",
                "currency_column" => "cur_htg",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "66",
                "aplha_code2" => "HU",
                "aplha_code3" => "HUN",
                "numeric_code" => "348",
                "country_name" => "Hungary",
                "currency_name" => "Hungarian Forint",
                "currency_code" => "HUF",
                "currency_symbol" => "Ft",
                "currency_column" => "cur_huf",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "67",
                "aplha_code2" => "ID",
                "aplha_code3" => "IDN",
                "numeric_code" => "360",
                "country_name" => "Indonesia",
                "currency_name" => "Indonesian rupiah",
                "currency_code" => "IDR",
                "currency_symbol" => "Rp",
                "currency_column" => "cur_idr",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "68",
                "aplha_code2" => "IE",
                "aplha_code3" => "IRL",
                "numeric_code" => "372",
                "country_name" => "Ireland",
                "currency_name" => "Euro",
                "currency_code" => "EUR",
                "currency_symbol" => "€",
                "currency_column" => "cur_eur_ie",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "69",
                "aplha_code2" => "IL",
                "aplha_code3" => "ISR",
                "numeric_code" => "376",
                "country_name" => "Israel",
                "currency_name" => "Israeli New Shekel",
                "currency_code" => "ILS",
                "currency_symbol" => "₪",
                "currency_column" => "cur_ils",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "70",
                "aplha_code2" => "IM",
                "aplha_code3" => "IMN",
                "numeric_code" => "833",
                "country_name" => "Isle of Man",
                "currency_name" => "Pound",
                "currency_code" => "GBP",
                "currency_symbol" => "£",
                "currency_column" => "cur_gbp_im",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "71",
                "aplha_code2" => "IN",
                "aplha_code3" => "IND",
                "numeric_code" => "356",
                "country_name" => "India",
                "currency_name" => "Indian rupee",
                "currency_code" => "INR",
                "currency_symbol" => "₹",
                "currency_column" => "cur_inr",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "72",
                "aplha_code2" => "IO",
                "aplha_code3" => "IOT",
                "numeric_code" => "86",
                "country_name" => "British Indian Ocean Territory",
                "currency_name" => "Pound",
                "currency_code" => "GBP",
                "currency_symbol" => "£",
                "currency_column" => "cur_gbp_io",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "73",
                "aplha_code2" => "IQ",
                "aplha_code3" => "IRQ",
                "numeric_code" => "368",
                "country_name" => "Iraq",
                "currency_name" => "Iraqi Dinar",
                "currency_code" => "IQD",
                "currency_symbol" => "IQD",
                "currency_column" => "cur_iqd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "74",
                "aplha_code2" => "IR",
                "aplha_code3" => "IRN",
                "numeric_code" => "364",
                "country_name" => "Iran, Islamic Republic of",
                "currency_name" => "Iranian Rial",
                "currency_code" => "IRR",
                "currency_symbol" => "IRR",
                "currency_column" => "cur_irr",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "75",
                "aplha_code2" => "IS",
                "aplha_code3" => "ISL",
                "numeric_code" => "352",
                "country_name" => "Iceland",
                "currency_name" => "Icelandic króna",
                "currency_code" => "ISK",
                "currency_symbol" => "Íkr",
                "currency_column" => "cur_isk",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "76",
                "aplha_code2" => "IT",
                "aplha_code3" => "ITA",
                "numeric_code" => "380",
                "country_name" => "Italy",
                "currency_name" => "Euro",
                "currency_code" => "EUR",
                "currency_symbol" => "€",
                "currency_column" => "cur_eur_it",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "77",
                "aplha_code2" => "JM",
                "aplha_code3" => "JAM",
                "numeric_code" => "388",
                "country_name" => "Jamaica",
                "currency_name" => "Jamaican dollar",
                "currency_code" => "JMD",
                "currency_symbol" => "J$",
                "currency_column" => "cur_jmd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "78",
                "aplha_code2" => "JO",
                "aplha_code3" => "JOR",
                "numeric_code" => "400",
                "country_name" => "Jordan",
                "currency_name" => "Jordanian Dinar",
                "currency_code" => "JOD",
                "currency_symbol" => "JOD",
                "currency_column" => "cur_jod",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "79",
                "aplha_code2" => "JP",
                "aplha_code3" => "JPN",
                "numeric_code" => "392",
                "country_name" => "Japan",
                "currency_name" => "Japanese Yen",
                "currency_code" => "JPY",
                "currency_symbol" => "¥",
                "currency_column" => "cur_jpy",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "80",
                "aplha_code2" => "KE",
                "aplha_code3" => "KEN",
                "numeric_code" => "404",
                "country_name" => "Kenya",
                "currency_name" => "Kenyan Shilling",
                "currency_code" => "KES",
                "currency_symbol" => "K",
                "currency_column" => "cur_kes",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "81",
                "aplha_code2" => "KG",
                "aplha_code3" => "KGZ",
                "numeric_code" => "417",
                "country_name" => "Kyrgyzstan",
                "currency_name" => "Kyrgystani Som",
                "currency_code" => "KGS",
                "currency_symbol" => "Лв",
                "currency_column" => "cur_kgs",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "82",
                "aplha_code2" => "KH",
                "aplha_code3" => "KHM",
                "numeric_code" => "116",
                "country_name" => "Cambodia",
                "currency_name" => "Cambodian riel",
                "currency_code" => "KHR",
                "currency_symbol" => "KHR",
                "currency_column" => "cur_khr",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "83",
                "aplha_code2" => "KI",
                "aplha_code3" => "KIR",
                "numeric_code" => "296",
                "country_name" => "Kiribati",
                "currency_name" => "Australian Dollar",
                "currency_code" => "AUD",
                "currency_symbol" => "A$",
                "currency_column" => "cur_aud_ki",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "84",
                "aplha_code2" => "KR",
                "aplha_code3" => "KOR",
                "numeric_code" => "410",
                "country_name" => "Korea, Republic of",
                "currency_name" => "South Korean Won",
                "currency_code" => "KRW",
                "currency_symbol" => "₩",
                "currency_column" => "cur_krw",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "85",
                "aplha_code2" => "KW",
                "aplha_code3" => "KWT",
                "numeric_code" => "414",
                "country_name" => "Kuwait",
                "currency_name" => "Kuwaiti Dinar",
                "currency_code" => "KWD",
                "currency_symbol" => "KD",
                "currency_column" => "cur_kwd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "86",
                "aplha_code2" => "KY",
                "aplha_code3" => "CYM",
                "numeric_code" => "136",
                "country_name" => "Cayman Islands",
                "currency_name" => "Cayman Islands Dollar",
                "currency_code" => "KYD",
                "currency_symbol" => "C$",
                "currency_column" => "cur_kyd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "87",
                "aplha_code2" => "KZ",
                "aplha_code3" => "KAZ",
                "numeric_code" => "398",
                "country_name" => "Kazakhstan",
                "currency_name" => "Kazakhstani tenge",
                "currency_code" => "KZT",
                "currency_symbol" => "₸",
                "currency_column" => "cur_kzt",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "88",
                "aplha_code2" => "LA",
                "aplha_code3" => "LAO",
                "numeric_code" => "418",
                "country_name" => "Lao People's Democratic Republic",
                "currency_name" => "Laotian Kip",
                "currency_code" => "LAK",
                "currency_symbol" => "₭",
                "currency_column" => "cur_lak",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "89",
                "aplha_code2" => "LB",
                "aplha_code3" => "LBN",
                "numeric_code" => "422",
                "country_name" => "Lebanon",
                "currency_name" => "Lebanese pound",
                "currency_code" => "LBP",
                "currency_symbol" => "L£",
                "currency_column" => "cur_lbp",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "90",
                "aplha_code2" => "LK",
                "aplha_code3" => "LKA",
                "numeric_code" => "144",
                "country_name" => "Sri Lanka",
                "currency_name" => "Sri Lankan Rupee",
                "currency_code" => "LKR",
                "currency_symbol" => "Rs. ",
                "currency_column" => "cur_lkr",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "91",
                "aplha_code2" => "LR",
                "aplha_code3" => "LBR",
                "numeric_code" => "430",
                "country_name" => "Liberia",
                "currency_name" => "Liberian Dollar",
                "currency_code" => "LRD",
                "currency_symbol" => "L$",
                "currency_column" => "cur_lrd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "92",
                "aplha_code2" => "LS",
                "aplha_code3" => "LSO",
                "numeric_code" => "426",
                "country_name" => "Lesotho",
                "currency_name" => "Lesotho Loti",
                "currency_code" => "LSL",
                "currency_symbol" => "L",
                "currency_column" => "cur_lsl",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "93",
                "aplha_code2" => "LT",
                "aplha_code3" => "LTU",
                "numeric_code" => "440",
                "country_name" => "Lithuania",
                "currency_name" => "Euro",
                "currency_code" => "EUR",
                "currency_symbol" => "€",
                "currency_column" => "cur_eur_lt",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "94",
                "aplha_code2" => "LU",
                "aplha_code3" => "LUX",
                "numeric_code" => "442",
                "country_name" => "Luxembourg",
                "currency_name" => "Euro",
                "currency_code" => "EUR",
                "currency_symbol" => "€",
                "currency_column" => "cur_eur_lu",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "95",
                "aplha_code2" => "LV",
                "aplha_code3" => "LVA",
                "numeric_code" => "428",
                "country_name" => "Latvia",
                "currency_name" => "Euro",
                "currency_code" => "EUR",
                "currency_symbol" => "€",
                "currency_column" => "cur_eur_lv",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "96",
                "aplha_code2" => "LY",
                "aplha_code3" => "LBY",
                "numeric_code" => "434",
                "country_name" => "Libya",
                "currency_name" => "Libyan dinar",
                "currency_code" => "LYD",
                "currency_symbol" => "LD",
                "currency_column" => "cur_lyd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "97",
                "aplha_code2" => "MA",
                "aplha_code3" => "MAR",
                "numeric_code" => "504",
                "country_name" => "Morocco",
                "currency_name" => "Moroccan Dirham",
                "currency_code" => "MAD",
                "currency_symbol" => "MAD",
                "currency_column" => "cur_mad",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "98",
                "aplha_code2" => "MC",
                "aplha_code3" => "MCO",
                "numeric_code" => "492",
                "country_name" => "Monaco",
                "currency_name" => "Euro",
                "currency_code" => "EUR",
                "currency_symbol" => "€",
                "currency_column" => "cur_eur_mc",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "99",
                "aplha_code2" => "MD",
                "aplha_code3" => "MDA",
                "numeric_code" => "498",
                "country_name" => "Moldova, Republic of",
                "currency_name" => "Moldovan Leu",
                "currency_code" => "MDL",
                "currency_symbol" => "L",
                "currency_column" => "cur_mdl",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "100",
                "aplha_code2" => "ME",
                "aplha_code3" => "MNE",
                "numeric_code" => "499",
                "country_name" => "Montenegro",
                "currency_name" => "Euro",
                "currency_code" => "EUR",
                "currency_symbol" => "€",
                "currency_column" => "cur_eur_me",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "101",
                "aplha_code2" => "MG",
                "aplha_code3" => "MDG",
                "numeric_code" => "450",
                "country_name" => "Madagascar",
                "currency_name" => "Malagasy Ariary",
                "currency_code" => "MGA",
                "currency_symbol" => "Ar",
                "currency_column" => "cur_mga",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "102",
                "aplha_code2" => "MK",
                "aplha_code3" => "MKD",
                "numeric_code" => "807",
                "country_name" => "North Macedonia",
                "currency_name" => "Macedonian Denar",
                "currency_code" => "MKD",
                "currency_symbol" => "den",
                "currency_column" => "cur_mkd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "103",
                "aplha_code2" => "MM",
                "aplha_code3" => "MMR",
                "numeric_code" => "104",
                "country_name" => "Myanmar",
                "currency_name" => "Myanma Kyat",
                "currency_code" => "MMK",
                "currency_symbol" => "K",
                "currency_column" => "cur_mmk",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "104",
                "aplha_code2" => "MO",
                "aplha_code3" => "MAC",
                "numeric_code" => "446",
                "country_name" => "Macao",
                "currency_name" => "Macanese Pataca",
                "currency_code" => "MOP",
                "currency_symbol" => "MOP",
                "currency_column" => "cur_mop",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "105",
                "aplha_code2" => "MT",
                "aplha_code3" => "MLT",
                "numeric_code" => "470",
                "country_name" => "Malta",
                "currency_name" => "Euro",
                "currency_code" => "EUR",
                "currency_symbol" => "€",
                "currency_column" => "cur_eur_mt",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "106",
                "aplha_code2" => "MU",
                "aplha_code3" => "MUS",
                "numeric_code" => "480",
                "country_name" => "Mauritius",
                "currency_name" => "Mauritian Rupee",
                "currency_code" => "MUR",
                "currency_symbol" => "Rs.",
                "currency_column" => "cur_mur",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "107",
                "aplha_code2" => "MV",
                "aplha_code3" => "MDV",
                "numeric_code" => "462",
                "country_name" => "Maldives",
                "currency_name" => "Maldivian Rufiyaa",
                "currency_code" => "MVR",
                "currency_symbol" => "Rf",
                "currency_column" => "cur_mvr",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "108",
                "aplha_code2" => "MW",
                "aplha_code3" => "MWI",
                "numeric_code" => "454",
                "country_name" => "Malawi",
                "currency_name" => "Malawian Kwacha",
                "currency_code" => "MWK",
                "currency_symbol" => "MK",
                "currency_column" => "cur_mwk",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "109",
                "aplha_code2" => "MX",
                "aplha_code3" => "MEX",
                "numeric_code" => "484",
                "country_name" => "Mexico",
                "currency_name" => "Mexican Peso",
                "currency_code" => "MXN",
                "currency_symbol" => "Mex$",
                "currency_column" => "cur_mxn",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "110",
                "aplha_code2" => "MY",
                "aplha_code3" => "MYS",
                "numeric_code" => "458",
                "country_name" => "Malaysia",
                "currency_name" => "Malaysian Ringgit",
                "currency_code" => "MYR",
                "currency_symbol" => "RM",
                "currency_column" => "cur_myr",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "111",
                "aplha_code2" => "MZ",
                "aplha_code3" => "MOZ",
                "numeric_code" => "508",
                "country_name" => "Mozambique",
                "currency_name" => "Mozambican Metical",
                "currency_code" => "MZN",
                "currency_symbol" => "MT",
                "currency_column" => "cur_mzn",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "112",
                "aplha_code2" => "NA",
                "aplha_code3" => "NAM",
                "numeric_code" => "516",
                "country_name" => "Namibia",
                "currency_name" => "Namibian Dollar",
                "currency_code" => "NAD",
                "currency_symbol" => "NA$",
                "currency_column" => "cur_nad",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "113",
                "aplha_code2" => "NC",
                "aplha_code3" => "NCL",
                "numeric_code" => "540",
                "country_name" => "New Caledonia",
                "currency_name" => "CFP Franc",
                "currency_code" => "XPF",
                "currency_symbol" => "₣",
                "currency_column" => "cur_nc_xpf",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "114",
                "aplha_code2" => "NG",
                "aplha_code3" => "NGA",
                "numeric_code" => "566",
                "country_name" => "Nigeria",
                "currency_name" => "Nigerian Naira",
                "currency_code" => "NGN",
                "currency_symbol" => "₦",
                "currency_column" => "cur_ngn",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "115",
                "aplha_code2" => "NI",
                "aplha_code3" => "NIC",
                "numeric_code" => "558",
                "country_name" => "Nicaragua",
                "currency_name" => "Nicaraguan Córdoba",
                "currency_code" => "NIO",
                "currency_symbol" => "C$",
                "currency_column" => "cur_nio",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "116",
                "aplha_code2" => "NL",
                "aplha_code3" => "NLD",
                "numeric_code" => "528",
                "country_name" => "Netherlands",
                "currency_name" => "Euro",
                "currency_code" => "EUR",
                "currency_symbol" => "€",
                "currency_column" => "cur_eur_nl",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "117",
                "aplha_code2" => "NO",
                "aplha_code3" => "NOR",
                "numeric_code" => "578",
                "country_name" => "Norway",
                "currency_name" => "Norwegian Krone",
                "currency_code" => "NOK",
                "currency_symbol" => "kr",
                "currency_column" => "cur_nok",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "118",
                "aplha_code2" => "NP",
                "aplha_code3" => "NPL",
                "numeric_code" => "524",
                "country_name" => "Nepal",
                "currency_name" => "Nepalese Rupee",
                "currency_code" => "NPR",
                "currency_symbol" => "Rs",
                "currency_column" => "cur_npr",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "119",
                "aplha_code2" => "NR",
                "aplha_code3" => "NRU",
                "numeric_code" => "520",
                "country_name" => "Nauru",
                "currency_name" => "Australian Dollar",
                "currency_code" => "AUD",
                "currency_symbol" => "A$",
                "currency_column" => "cur_aud_nr",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "120",
                "aplha_code2" => "NU",
                "aplha_code3" => "NIU",
                "numeric_code" => "570",
                "country_name" => "Niue",
                "currency_name" => "New Zealand Dollar",
                "currency_code" => "NZD",
                "currency_symbol" => "NZ$",
                "currency_column" => "cur_nu_nzd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "121",
                "aplha_code2" => "NZ",
                "aplha_code3" => "NZL",
                "numeric_code" => "554",
                "country_name" => "New Zealand",
                "currency_name" => "New Zealand Dollar",
                "currency_code" => "NZD",
                "currency_symbol" => "NZ$",
                "currency_column" => "cur_nzd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "122",
                "aplha_code2" => "OM",
                "aplha_code3" => "OMN",
                "numeric_code" => "512",
                "country_name" => "Oman",
                "currency_name" => "Omani Rial",
                "currency_code" => "OMR",
                "currency_symbol" => "ر",
                "currency_column" => "cur_omr",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "123",
                "aplha_code2" => "PA",
                "aplha_code3" => "PAN",
                "numeric_code" => "591",
                "country_name" => "Panama",
                "currency_name" => "Panamanian Balboa",
                "currency_code" => "PAB",
                "currency_symbol" => "PAB",
                "currency_column" => "cur_pab",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "124",
                "aplha_code2" => "PE",
                "aplha_code3" => "PER",
                "numeric_code" => "604",
                "country_name" => "Peru",
                "currency_name" => "Peruvian Nuevo Sol",
                "currency_code" => "PEN",
                "currency_symbol" => "PEN",
                "currency_column" => "cur_pen",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "125",
                "aplha_code2" => "PF",
                "aplha_code3" => "PYF",
                "numeric_code" => "258",
                "country_name" => "French Polynesia",
                "currency_name" => "CFP Franc",
                "currency_code" => "XPF",
                "currency_symbol" => "₣",
                "currency_column" => "cur_pf_xpf",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "126",
                "aplha_code2" => "PG",
                "aplha_code3" => "PNG",
                "numeric_code" => "598",
                "country_name" => "Papua New Guinea",
                "currency_name" => "Papua New Guinean Kina",
                "currency_code" => "PGK",
                "currency_symbol" => "K",
                "currency_column" => "cur_pgk",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "127",
                "aplha_code2" => "PH",
                "aplha_code3" => "PHL",
                "numeric_code" => "608",
                "country_name" => "Philippines",
                "currency_name" => "Philippine Peso",
                "currency_code" => "PHP",
                "currency_symbol" => "₱",
                "currency_column" => "cur_php",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "128",
                "aplha_code2" => "PK",
                "aplha_code3" => "PAK",
                "numeric_code" => "586",
                "country_name" => "Pakistan",
                "currency_name" => "Pakistani Rupee",
                "currency_code" => "PKR",
                "currency_symbol" => "Rs",
                "currency_column" => "cur_pkr",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "129",
                "aplha_code2" => "PL",
                "aplha_code3" => "POL",
                "numeric_code" => "616",
                "country_name" => "Poland",
                "currency_name" => "Polish Zloty",
                "currency_code" => "PLN",
                "currency_symbol" => "zł",
                "currency_column" => "cur_pln",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "130",
                "aplha_code2" => "PN",
                "aplha_code3" => "PCN",
                "numeric_code" => "612",
                "country_name" => "Pitcairn",
                "currency_name" => "New Zealand Dollar",
                "currency_code" => "NZD",
                "currency_symbol" => "NZ$",
                "currency_column" => "cur_nu_nzd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "131",
                "aplha_code2" => "PT",
                "aplha_code3" => "PRT",
                "numeric_code" => "620",
                "country_name" => "Portugal",
                "currency_name" => "Euro",
                "currency_code" => "EUR",
                "currency_symbol" => "€",
                "currency_column" => "cur_eur_pt",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "132",
                "aplha_code2" => "PY",
                "aplha_code3" => "PRY",
                "numeric_code" => "600",
                "country_name" => "Paraguay",
                "currency_name" => "Paraguayan Guarani",
                "currency_code" => "PYG",
                "currency_symbol" => "₲",
                "currency_column" => "cur_pyg",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "133",
                "aplha_code2" => "QA",
                "aplha_code3" => "QAT",
                "numeric_code" => "634",
                "country_name" => "Qatar",
                "currency_name" => "Qatari Rial",
                "currency_code" => "QAR",
                "currency_symbol" => "QR",
                "currency_column" => "cur_qar",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "134",
                "aplha_code2" => "RO",
                "aplha_code3" => "ROU",
                "numeric_code" => "642",
                "country_name" => "Romania",
                "currency_name" => "Romanian Leu",
                "currency_code" => "RON",
                "currency_symbol" => "lei",
                "currency_column" => "cur_ron",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "135",
                "aplha_code2" => "RS",
                "aplha_code3" => "SRB",
                "numeric_code" => "688",
                "country_name" => "Serbia",
                "currency_name" => "Serbian Dinar",
                "currency_code" => "RSD",
                "currency_symbol" => "din",
                "currency_column" => "cur_rsd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "136",
                "aplha_code2" => "RU",
                "aplha_code3" => "RUS",
                "numeric_code" => "643",
                "country_name" => "Russian Federation",
                "currency_name" => "Russian Ruble",
                "currency_code" => "RUB",
                "currency_symbol" => "₽",
                "currency_column" => "cur_rub",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "137",
                "aplha_code2" => "RW",
                "aplha_code3" => "RWA",
                "numeric_code" => "646",
                "country_name" => "Rwanda",
                "currency_name" => "Rwandan Franc",
                "currency_code" => "RWF",
                "currency_symbol" => "RF",
                "currency_column" => "cur_rwf",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "138",
                "aplha_code2" => "SA",
                "aplha_code3" => "SAU",
                "numeric_code" => "682",
                "country_name" => "Saudi Arabia",
                "currency_name" => "Saudi Riyal",
                "currency_code" => "SAR",
                "currency_symbol" => "SR",
                "currency_column" => "cur_sar",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "139",
                "aplha_code2" => "SB",
                "aplha_code3" => "SLB",
                "numeric_code" => "90",
                "country_name" => "Solomon Islands",
                "currency_name" => "Solomon Islands Dollar",
                "currency_code" => "SBD",
                "currency_symbol" => "SI$",
                "currency_column" => "cur_sbd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "140",
                "aplha_code2" => "SC",
                "aplha_code3" => "SYC",
                "numeric_code" => "690",
                "country_name" => "Seychelles",
                "currency_name" => "Seychellois Rupee",
                "currency_code" => "SCR",
                "currency_symbol" => "SR",
                "currency_column" => "cur_scr",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "141",
                "aplha_code2" => "SD",
                "aplha_code3" => "SDN",
                "numeric_code" => "729",
                "country_name" => "Sudan",
                "currency_name" => "Sudanese Pound",
                "currency_code" => "SDG",
                "currency_symbol" => "SD",
                "currency_column" => "cur_sdg",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "142",
                "aplha_code2" => "SE",
                "aplha_code3" => "SWE",
                "numeric_code" => "752",
                "country_name" => "Sweden",
                "currency_name" => "Swedish Krona",
                "currency_code" => "SEK",
                "currency_symbol" => "kr",
                "currency_column" => "cur_sek",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "143",
                "aplha_code2" => "SG",
                "aplha_code3" => "SGP",
                "numeric_code" => "702",
                "country_name" => "Singapore",
                "currency_name" => "Singapore Dollar",
                "currency_code" => "SGD",
                "currency_symbol" => "S$",
                "currency_column" => "cur_sgd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "144",
                "aplha_code2" => "SI",
                "aplha_code3" => "SVN",
                "numeric_code" => "705",
                "country_name" => "Slovenia",
                "currency_name" => "Euro",
                "currency_code" => "EUR",
                "currency_symbol" => "€",
                "currency_column" => "cur_eur_si",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "145",
                "aplha_code2" => "SK",
                "aplha_code3" => "SVK",
                "numeric_code" => "703",
                "country_name" => "Slovakia",
                "currency_name" => "Euro",
                "currency_code" => "EUR",
                "currency_symbol" => "€",
                "currency_column" => "cur_eur_sk",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "146",
                "aplha_code2" => "SL",
                "aplha_code3" => "SLE",
                "numeric_code" => "694",
                "country_name" => "Sierra Leone",
                "currency_name" => "Sierra Leonean Leone",
                "currency_code" => "SLL",
                "currency_symbol" => "Le",
                "currency_column" => "cur_sll",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "147",
                "aplha_code2" => "SO",
                "aplha_code3" => "SOM",
                "numeric_code" => "706",
                "country_name" => "Somalia",
                "currency_name" => "Somali Shilling",
                "currency_code" => "SOS",
                "currency_symbol" => "Sh",
                "currency_column" => "cur_sos",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "148",
                "aplha_code2" => "SR",
                "aplha_code3" => "SUR",
                "numeric_code" => "740",
                "country_name" => "Suriname",
                "currency_name" => "Surinamese Dollar",
                "currency_code" => "SRD",
                "currency_symbol" => "Sr$",
                "currency_column" => "cur_srd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "149",
                "aplha_code2" => "SS",
                "aplha_code3" => "SSD",
                "numeric_code" => "728",
                "country_name" => "South Sudan",
                "currency_name" => "Sudanese Pound",
                "currency_code" => "SDG",
                "currency_symbol" => "SD",
                "currency_column" => "cur_sdg",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "150",
                "aplha_code2" => "SZ",
                "aplha_code3" => "SWZ",
                "numeric_code" => "748",
                "country_name" => "Swaziland",
                "currency_name" => "Swazi Lilangeni",
                "currency_code" => "SZL",
                "currency_symbol" => "E",
                "currency_column" => "cur_szl",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "151",
                "aplha_code2" => "TH",
                "aplha_code3" => "THA",
                "numeric_code" => "764",
                "country_name" => "Thailand",
                "currency_name" => "Thai Baht",
                "currency_code" => "THB",
                "currency_symbol" => "฿",
                "currency_column" => "cur_thb",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "152",
                "aplha_code2" => "TJ",
                "aplha_code3" => "TJK",
                "numeric_code" => "762",
                "country_name" => "Tajikistan",
                "currency_name" => "Tajikistani Somoni",
                "currency_code" => "TJS",
                "currency_symbol" => "ЅM",
                "currency_column" => "cur_tjs",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "153",
                "aplha_code2" => "TM",
                "aplha_code3" => "TKM",
                "numeric_code" => "795",
                "country_name" => "Turkmenistan",
                "currency_name" => "Turkmenistani Manat",
                "currency_code" => "TMT",
                "currency_symbol" => "T",
                "currency_column" => "cur_tmt",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "154",
                "aplha_code2" => "TN",
                "aplha_code3" => "TUN",
                "numeric_code" => "788",
                "country_name" => "Tunisia",
                "currency_name" => "Tunisian Dinar",
                "currency_code" => "TND",
                "currency_symbol" => "DT",
                "currency_column" => "cur_tnd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "155",
                "aplha_code2" => "TO",
                "aplha_code3" => "TON",
                "numeric_code" => "776",
                "country_name" => "Tonga",
                "currency_name" => "Tongan Paʻanga",
                "currency_code" => "TOP",
                "currency_symbol" => "T$",
                "currency_column" => "cur_top",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "156",
                "aplha_code2" => "TR",
                "aplha_code3" => "TUR",
                "numeric_code" => "792",
                "country_name" => "Turkey",
                "currency_name" => "Turkish Lira",
                "currency_code" => "TRY",
                "currency_symbol" => "TL",
                "currency_column" => "cur_try",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "157",
                "aplha_code2" => "TT",
                "aplha_code3" => "TTO",
                "numeric_code" => "780",
                "country_name" => "Trinidad and Tobago",
                "currency_name" => "Trinidad and Tobago Dollar",
                "currency_code" => "TTD",
                "currency_symbol" => "TT$",
                "currency_column" => "cur_ttd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "158",
                "aplha_code2" => "TV",
                "aplha_code3" => "TUV",
                "numeric_code" => "798",
                "country_name" => "Tuvalu",
                "currency_name" => "Australian Dollar",
                "currency_code" => "AUD",
                "currency_symbol" => "A$",
                "currency_column" => "cur_aud_tv",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "159",
                "aplha_code2" => "TW",
                "aplha_code3" => "TWN",
                "numeric_code" => "158",
                "country_name" => "Taiwan, Province of China",
                "currency_name" => "New Taiwan Dollar",
                "currency_code" => "TWD",
                "currency_symbol" => "NT$",
                "currency_column" => "cur_twd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "160",
                "aplha_code2" => "TZ",
                "aplha_code3" => "TZA",
                "numeric_code" => "834",
                "country_name" => "Tanzania, United Republic of",
                "currency_name" => "Tanzanian Shilling",
                "currency_code" => "TZS",
                "currency_symbol" => "TSh",
                "currency_column" => "cur_tzs",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "161",
                "aplha_code2" => "UA",
                "aplha_code3" => "UKR",
                "numeric_code" => "804",
                "country_name" => "Ukraine",
                "currency_name" => "Ukrainian Hryvnia",
                "currency_code" => "UAH",
                "currency_symbol" => "₴",
                "currency_column" => "cur_uah",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "162",
                "aplha_code2" => "UG",
                "aplha_code3" => "UGA",
                "numeric_code" => "800",
                "country_name" => "Uganda",
                "currency_name" => "Ugandan Shilling",
                "currency_code" => "UGX",
                "currency_symbol" => "Ush",
                "currency_column" => "cur_ugx",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "163",
                "aplha_code2" => "UY",
                "aplha_code3" => "URY",
                "numeric_code" => "858",
                "country_name" => "Uruguay",
                "currency_name" => "Uruguayan peso",
                "currency_code" => "UYU",
                "currency_symbol" => "",
                "currency_column" => "cur_uyu",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "164",
                "aplha_code2" => "UZ",
                "aplha_code3" => "UZB",
                "numeric_code" => "860",
                "country_name" => "Uzbekistan",
                "currency_name" => "Uzbekistan Som",
                "currency_code" => "UZS",
                "currency_symbol" => "so'm",
                "currency_column" => "cur_uzs",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "165",
                "aplha_code2" => "VN",
                "aplha_code3" => "VNM",
                "numeric_code" => "704",
                "country_name" => "Viet Nam",
                "currency_name" => "Vietnamese Dong",
                "currency_code" => "VND",
                "currency_symbol" => "₫",
                "currency_column" => "cur_vnd",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "166",
                "aplha_code2" => "WF",
                "aplha_code3" => "WLF",
                "numeric_code" => "876",
                "country_name" => "Wallis and Futuna",
                "currency_name" => "CFP Franc",
                "currency_code" => "XPF",
                "currency_symbol" => "₣",
                "currency_column" => "cur_wf_xpf",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "167",
                "aplha_code2" => "YE",
                "aplha_code3" => "YEM",
                "numeric_code" => "887",
                "country_name" => "Yemen",
                "currency_name" => "Yemeni Rial",
                "currency_code" => "YER",
                "currency_symbol" => "Rial",
                "currency_column" => "cur_yer",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "168",
                "aplha_code2" => "ZA",
                "aplha_code3" => "ZAF",
                "numeric_code" => "710",
                "country_name" => "South Africa",
                "currency_name" => "South African Rand",
                "currency_code" => "ZAR",
                "currency_symbol" => "R",
                "currency_column" => "cur_zar",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "169",
                "aplha_code2" => "ZM",
                "aplha_code3" => "ZMB",
                "numeric_code" => "894",
                "country_name" => "Zambia",
                "currency_name" => "Zambian Kwacha",
                "currency_code" => "ZMW",
                "currency_symbol" => "ZK",
                "currency_column" => "cur_zmw",
                "added_by" => "1",
                "status" => "1"
            ],
            [
                "id" => "170",
                "aplha_code2" => "US",
                "aplha_code3" => "USA",
                "numeric_code" => "840",
                "country_name" => "United States",
                "currency_name" => "US Dollar",
                "currency_code" => "USD",
                "currency_symbol" => "$",
                "currency_column" => "sale_price",
                "added_by" => "1",
                "status" => "1"
            ]
        ];

        CountryCurrencies::insert($countrycurrencies);
    }
}
